#ifndef	DEF_CONSTANTES
#define	DEF_CONSTANTES

#define TAILLE_BLOC		34
#define	NB_BLOCS_LARGEUR	15
#define NB_BLOCS_HAUTEUR	15
#define WIDHT			TAILLE_BLOC * NB_BLOCS_LARGEUR
#define LENGTH			TAILLE_BLOC * NB_BLOCS_HAUTEUR

enum{HAUT, BAS, GAUCHE, DROITE};
enum{VIDE, MUR, HEROS};

#endif
