#ifndef	DEF_CONSTANTES
#define	DEF_CONSTANTES

#define TAILLE_BLOC		34
#define	NB_BLOCS_LARGEUR	24
#define NB_BLOCS_HAUTEUR	24
#define WIDHT			TAILLE_BLOC * NB_BLOCS_LARGEUR
#define LENGTH			TAILLE_BLOC * NB_BLOCS_HAUTEUR

enum{HAUT, BAS, GAUCHE, DROITE};
enum{VIDE, MUR, HEROS, FIN, PACERELLE};

#endif
